#%RAML 1.0 NamedExample
value:
  links:
    self: /objects/123
  data: 
    - type: Object
      id: "123"
      attributes:
        value: abc123
    - type: Object
      id: "1234"
      attributes:
        value: abc1234
